part of 'mentor_report_simplified_screen.dart';

// Full-screen premium report opened from MentorReportSimplifiedScreen. NOTE: overlaps with _PremiumReportFullScreen in mentor_submission_premium_report.dart (same report, separate implementations).

/// Premium full report screen showing enhanced AI-generated insights
class _PremiumFullReportScreen extends StatelessWidget {
  final Map<String, dynamic> report;
  final String apprenticeName;
  final bool isCached;

  const _PremiumFullReportScreen({
    required this.report,
    required this.apprenticeName,
    this.isCached = false,
  });

  @override
  Widget build(BuildContext context) {
    // Extract sections from the premium report
    // The API returns: strengths_deep_dive, gaps_deep_dive, conversation_guide, biblical_knowledge_analysis
    final strengthsDeepDive = report['strengths_deep_dive'] as List<dynamic>?;
    final gapsDeepDive = report['gaps_deep_dive'] as List<dynamic>?;
    final execSummary = report['executive_summary'] as Map<String, dynamic>?;
    final conversationGuide = report['conversation_guide'] as Map<String, dynamic>?;
    final biblicalKnowledge = report['biblical_knowledge_analysis'] as Map<String, dynamic>?;
    final spiritualFormation = report['spiritual_formation_insights'] as List<dynamic>?;
    final meta = report['_meta'] as Map<String, dynamic>?;

    return Scaffold(
      backgroundColor: Colors.black,
      appBar: AppBar(
        backgroundColor: Colors.black,
        foregroundColor: Colors.white,
        title: const Text('Premium Full Report', style: TextStyle(color: Colors.white)),
        iconTheme: const IconThemeData(color: Colors.white),
        actions: [
          if (isCached)
            Tooltip(
              message: 'Loaded from cache',
              child: Padding(
                padding: const EdgeInsets.all(12),
                child: Icon(Icons.cached, color: Colors.amber.shade300),
              ),
            ),
        ],
      ),
      body: ListView(
        padding: const EdgeInsets.all(16),
        children: [
          // Premium badge header
          Container(
            padding: const EdgeInsets.all(12),
            decoration: BoxDecoration(
              gradient: LinearGradient(
                colors: [Colors.amber.shade900.withValues(alpha: 0.5), Colors.amber.shade900.withValues(alpha: 0.2)],
              ),
              borderRadius: BorderRadius.circular(12),
              border: Border.all(color: Colors.amber.shade700),
            ),
            child: Row(
              children: [
                Icon(Icons.auto_awesome, color: Colors.amber.shade400),
                const SizedBox(width: 8),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        'Premium Report for $apprenticeName',
                        style: TextStyle(
                          fontWeight: FontWeight.bold,
                          color: Colors.amber.shade200,
                        ),
                      ),
                      if (meta != null)
                        Text(
                          'Generated by ${meta['model'] ?? 'AI'} • ${meta['latency_ms'] ?? 0}ms',
                          style: TextStyle(fontSize: 11, color: Colors.amber.shade400),
                        ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          const SizedBox(height: 20),

          // Executive Summary
          if (execSummary != null) ...[
            _buildSectionHeader('Executive Summary', Icons.summarize),
            const SizedBox(height: 12),
            _buildExecutiveSummary(execSummary),
            const SizedBox(height: 20),
          ],

          // Strengths Deep Dive
          if (strengthsDeepDive != null && strengthsDeepDive.isNotEmpty) ...[
            _buildSectionHeader('Strengths Deep Dive', Icons.thumb_up),
            const SizedBox(height: 12),
            ...strengthsDeepDive.map((s) => _buildStrengthDeepDiveCard(s as Map<String, dynamic>)),
            const SizedBox(height: 20),
          ],

          // Gaps Deep Dive (with growth pathways)
          if (gapsDeepDive != null && gapsDeepDive.isNotEmpty) ...[
            _buildSectionHeader('Growth Areas Deep Dive', Icons.trending_up),
            const SizedBox(height: 12),
            ...gapsDeepDive.map((g) => _buildGapDeepDiveCard(g as Map<String, dynamic>)),
            const SizedBox(height: 20),
          ],

          // Conversation Guide
          if (conversationGuide != null) ...[
            _buildSectionHeader('Mentor Conversation Guide', Icons.chat),
            const SizedBox(height: 12),
            _buildConversationGuideSection(conversationGuide),
            const SizedBox(height: 20),
          ],

          // Biblical Knowledge Deep Dive
          if (biblicalKnowledge != null) ...[
            _buildSectionHeader('Biblical Knowledge Analysis', Icons.menu_book),
            const SizedBox(height: 12),
            _buildBiblicalKnowledgeSection(biblicalKnowledge),
            const SizedBox(height: 20),
          ],

          // Spiritual Formation Insights
          if (spiritualFormation != null && spiritualFormation.isNotEmpty) ...[
            _buildSectionHeader('Spiritual Formation Insights', Icons.self_improvement),
            const SizedBox(height: 12),
            ...spiritualFormation.map((s) => _buildSpiritualFormationCard(s as Map<String, dynamic>)),
            const SizedBox(height: 20),
          ],

          // Fallback: show raw JSON if structure is unexpected
          if (strengthsDeepDive == null && gapsDeepDive == null && conversationGuide == null) ...[
            _buildSectionHeader('Report Data', Icons.data_object),
            const SizedBox(height: 12),
            Card(
              color: Colors.grey[900],
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: SelectableText(
                  _prettyPrintJson(report),
                  style: TextStyle(fontSize: 12, fontFamily: 'monospace', color: Colors.grey[300]),
                ),
              ),
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildSectionHeader(String title, IconData icon) {
    return Row(
      children: [
        Icon(icon, size: 24, color: Colors.amber),
        const SizedBox(width: 8),
        Text(
          title,
          style: const TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: Colors.white),
        ),
      ],
    );
  }

  Widget _buildConversationGuideSection(Map<String, dynamic> guide) {
    final sessions = guide['sessions'] as List<dynamic>? ?? [];
    final openingQuestions = guide['opening_questions'] as List<dynamic>? ?? [];
    final topics = guide['suggested_topics'] as List<dynamic>? ?? [];

    return Card(
      color: Colors.grey[900],
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (openingQuestions.isNotEmpty) ...[
              const Text('Opening Questions:', style: TextStyle(fontWeight: FontWeight.w600, color: Colors.white)),
              const SizedBox(height: 8),
              ...openingQuestions.map((q) => Padding(
                padding: const EdgeInsets.only(bottom: 4),
                child: Text('• $q', style: TextStyle(fontSize: 13, color: Colors.grey[300])),
              )),
              const SizedBox(height: 12),
            ],
            if (sessions.isNotEmpty) ...[
              const Text('Session Structure:', style: TextStyle(fontWeight: FontWeight.w600, color: Colors.white)),
              const SizedBox(height: 8),
              ...sessions.asMap().entries.map((entry) {
                final session = entry.value as Map<String, dynamic>;
                return Padding(
                  padding: const EdgeInsets.only(bottom: 8),
                  child: Row(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      CircleAvatar(
                        radius: 12,
                        backgroundColor: Colors.blue.shade900,
                        child: Text('${entry.key + 1}', style: TextStyle(fontSize: 11, color: Colors.blue.shade200)),
                      ),
                      const SizedBox(width: 8),
                      Expanded(
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Text(session['focus'] ?? 'Session ${entry.key + 1}',
                                style: const TextStyle(fontWeight: FontWeight.w500, color: Colors.white)),
                            if (session['goal'] != null)
                              Text(session['goal'], style: TextStyle(fontSize: 12, color: Colors.grey[400])),
                          ],
                        ),
                      ),
                    ],
                  ),
                );
              }),
            ],
            if (topics.isNotEmpty) ...[
              const SizedBox(height: 12),
              const Text('Topics to Explore:', style: TextStyle(fontWeight: FontWeight.w600, color: Colors.white)),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                runSpacing: 4,
                children: topics.map((t) => Chip(
                  label: Text(t.toString(), style: TextStyle(fontSize: 12, color: Colors.blue.shade200)),
                  backgroundColor: Colors.blue.shade900.withValues(alpha: 0.5),
                )).toList(),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildBiblicalKnowledgeSection(Map<String, dynamic> knowledge) {
    final topicBreakdown = knowledge['topic_breakdown'] as List<dynamic>? ?? [];
    final weakAreas = knowledge['weak_areas'] as List<dynamic>? ?? [];
    final studyPlan = knowledge['study_plan'] as Map<String, dynamic>?;

    return Card(
      color: Colors.grey[900],
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            if (topicBreakdown.isNotEmpty) ...[
              const Text('Topic Performance:', style: TextStyle(fontWeight: FontWeight.w600, color: Colors.white)),
              const SizedBox(height: 8),
              ...topicBreakdown.take(5).map((topic) {
                if (topic is Map) {
                  final name = topic['topic'] ?? topic['name'] ?? 'Topic';
                  final score = topic['score'] ?? topic['percent'] ?? 0;
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 8),
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          children: [
                            Flexible(child: Text(name.toString(), style: TextStyle(fontSize: 13, color: Colors.grey[300]))),
                            Text('$score%', style: const TextStyle(fontWeight: FontWeight.w600, color: Colors.white)),
                          ],
                        ),
                        const SizedBox(height: 4),
                        LinearProgressIndicator(
                          value: (score is num ? score : 0) / 100,
                          backgroundColor: Colors.grey.shade800,
                          valueColor: AlwaysStoppedAnimation(
                            score > 70 ? Colors.green : score > 40 ? Colors.orange : Colors.red,
                          ),
                        ),
                      ],
                    ),
                  );
                }
                return const SizedBox.shrink();
              }),
            ],
            if (weakAreas.isNotEmpty) ...[
              const SizedBox(height: 12),
              const Text('Areas Needing Study:', style: TextStyle(fontWeight: FontWeight.w600, color: Colors.white)),
              const SizedBox(height: 8),
              Wrap(
                spacing: 8,
                runSpacing: 4,
                children: weakAreas.map((a) => Chip(
                  label: Text(a.toString(), style: TextStyle(fontSize: 11, color: Colors.orange.shade200)),
                  backgroundColor: Colors.orange.shade900.withValues(alpha: 0.3),
                  avatar: Icon(Icons.warning_amber, size: 14, color: Colors.orange.shade400),
                )).toList(),
              ),
            ],
            if (studyPlan != null) ...[
              const SizedBox(height: 12),
              const Text('Recommended Study Plan:', style: TextStyle(fontWeight: FontWeight.w600, color: Colors.white)),
              const SizedBox(height: 8),
              if (studyPlan['weeks'] != null)
                ...(studyPlan['weeks'] as List<dynamic>).asMap().entries.map((e) {
                  final week = e.value as Map<String, dynamic>;
                  return Padding(
                    padding: const EdgeInsets.only(bottom: 8),
                    child: Row(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Week ${e.key + 1}:', style: TextStyle(fontWeight: FontWeight.w500, fontSize: 13, color: Colors.amber)),
                        const SizedBox(width: 8),
                        Expanded(child: Text(week['focus'] ?? week.toString(), style: TextStyle(fontSize: 13, color: Colors.grey[300]))),
                      ],
                    ),
                  );
                }),
            ],
          ],
        ),
      ),
    );
  }

  String _prettyPrintJson(Map<String, dynamic> json) {
    try {
      const encoder = JsonEncoder.withIndent('  ');
      return encoder.convert(json);
    } catch (e) {
      return json.toString();
    }
  }

  Widget _buildExecutiveSummary(Map<String, dynamic> summary) {
    final healthScore = summary['health_score'] ?? 0;
    final healthBand = summary['health_band'] ?? 'Unknown';
    final oneLiner = summary['one_liner'] ?? '';
    final trajectory = summary['trajectory'] ?? 'stable';
    final trajectoryNote = summary['trajectory_note'] ?? '';

    return Card(
      color: Colors.amber.shade900.withValues(alpha: 0.3),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Container(
                  padding: const EdgeInsets.all(12),
                  decoration: BoxDecoration(
                    color: Colors.amber.shade800,
                    shape: BoxShape.circle,
                  ),
                  child: Text(
                    '$healthScore',
                    style: TextStyle(
                      fontSize: 24,
                      fontWeight: FontWeight.bold,
                      color: Colors.amber.shade100,
                    ),
                  ),
                ),
                const SizedBox(width: 16),
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(healthBand, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 18, color: Colors.white)),
                      Row(
                        children: [
                          Icon(
                            trajectory == 'upward' ? Icons.trending_up
                              : trajectory == 'downward' ? Icons.trending_down
                              : Icons.trending_flat,
                            size: 16,
                            color: trajectory == 'upward' ? Colors.green : trajectory == 'downward' ? Colors.red : Colors.grey,
                          ),
                          const SizedBox(width: 4),
                          Text(trajectory.toString().toUpperCase(),
                            style: TextStyle(fontSize: 12, color: Colors.grey[400])),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
            if (oneLiner.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text(oneLiner, style: TextStyle(fontSize: 14, fontStyle: FontStyle.italic, color: Colors.grey[300])),
            ],
            if (trajectoryNote.isNotEmpty) ...[
              const SizedBox(height: 8),
              Text(trajectoryNote, style: TextStyle(fontSize: 12, color: Colors.grey[400])),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildStrengthDeepDiveCard(Map<String, dynamic> strength) {
    final area = strength['area'] ?? 'Strength';
    final summary = strength['summary'] ?? '';
    final evidence = (strength['evidence'] as List<dynamic>?) ?? [];
    final maturityIndicator = strength['spiritual_maturity_indicator'] ?? '';
    final leverage = strength['how_to_leverage'] ?? '';
    final celebration = strength['celebration_talking_point'] ?? '';

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      color: Colors.green.shade900.withValues(alpha: 0.3),
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.star, color: Colors.green.shade400),
                const SizedBox(width: 8),
                Expanded(child: Text(area, style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.green.shade200))),
              ],
            ),
            if (summary.isNotEmpty) ...[
              const SizedBox(height: 8),
              Text(summary, style: TextStyle(fontSize: 14, color: Colors.grey[300])),
            ],
            if (evidence.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text('Evidence:', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.grey[400])),
              const SizedBox(height: 4),
              ...evidence.map((e) => Padding(
                padding: const EdgeInsets.only(left: 8, bottom: 4),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('• ', style: TextStyle(color: Colors.green.shade400)),
                    Expanded(child: Text(e.toString(), style: TextStyle(fontSize: 13, color: Colors.grey[300]))),
                  ],
                ),
              )),
            ],
            if (maturityIndicator.isNotEmpty) ...[
              const SizedBox(height: 12),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.green.shade900.withValues(alpha: 0.3),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('📖 Spiritual Insight', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.green.shade300)),
                    const SizedBox(height: 4),
                    Text(maturityIndicator, style: TextStyle(fontSize: 13, color: Colors.grey[300])),
                  ],
                ),
              ),
            ],
            if (leverage.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text('How to Leverage:', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.grey[400])),
              const SizedBox(height: 4),
              Text(leverage, style: TextStyle(fontSize: 13, color: Colors.grey[300])),
            ],
            if (celebration.isNotEmpty) ...[
              const SizedBox(height: 12),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.amber.shade900.withValues(alpha: 0.3),
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Colors.amber.shade700),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('💬 Celebration Talking Point', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.amber.shade300)),
                    const SizedBox(height: 4),
                    Text('"$celebration"', style: TextStyle(fontSize: 13, fontStyle: FontStyle.italic, color: Colors.grey[300])),
                  ],
                ),
              ),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildGapDeepDiveCard(Map<String, dynamic> gap) {
    final area = gap['area'] ?? 'Growth Area';
    final summary = gap['summary'] ?? '';
    final severity = gap['severity'] ?? 'moderate';
    final rootCause = gap['root_cause_analysis'] ?? '';
    final evidence = (gap['evidence'] as List<dynamic>?) ?? [];
    final biblical = gap['biblical_perspective'] ?? '';
    final whyMatters = gap['why_it_matters'] ?? '';
    final pathway = gap['growth_pathway'] as Map<String, dynamic>?;

    final severityColor = severity == 'critical' ? Colors.red
        : severity == 'moderate' ? Colors.orange
        : Colors.yellow;

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      color: Colors.grey[900],
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.trending_up, color: severityColor.shade400),
                const SizedBox(width: 8),
                Expanded(child: Text(area, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.white))),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: severityColor.shade900.withValues(alpha: 0.5),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(severity.toString().toUpperCase(),
                    style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: severityColor.shade300)),
                ),
              ],
            ),
            if (summary.isNotEmpty) ...[
              const SizedBox(height: 8),
              Text(summary, style: TextStyle(fontSize: 14, color: Colors.grey[300])),
            ],
            if (rootCause.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text('Root Cause:', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.grey[400])),
              const SizedBox(height: 4),
              Text(rootCause, style: TextStyle(fontSize: 13, color: Colors.grey[300])),
            ],
            if (evidence.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text('Evidence:', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.grey[400])),
              const SizedBox(height: 4),
              ...evidence.map((e) => Padding(
                padding: const EdgeInsets.only(left: 8, bottom: 4),
                child: Row(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('• ', style: TextStyle(color: severityColor.shade400)),
                    Expanded(child: Text(e.toString(), style: TextStyle(fontSize: 13, color: Colors.grey[300]))),
                  ],
                ),
              )),
            ],
            if (biblical.isNotEmpty) ...[
              const SizedBox(height: 12),
              Container(
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.blue.shade900.withValues(alpha: 0.3),
                  borderRadius: BorderRadius.circular(8),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text('📖 Biblical Perspective', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.blue.shade300)),
                    const SizedBox(height: 4),
                    Text(biblical, style: TextStyle(fontSize: 13, color: Colors.grey[300])),
                  ],
                ),
              ),
            ],
            if (whyMatters.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text('Why It Matters:', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.grey[400])),
              const SizedBox(height: 4),
              Text(whyMatters, style: TextStyle(fontSize: 13, color: Colors.grey[300])),
            ],
            if (pathway != null) ...[
              const SizedBox(height: 16),
              const Text('🎯 Growth Pathway', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: Colors.white)),
              const SizedBox(height: 8),
              _buildGrowthPhase(pathway['phase_1_weeks_1_4'] as Map<String, dynamic>?, 'Weeks 1-4', Colors.green),
              _buildGrowthPhase(pathway['phase_2_weeks_5_8'] as Map<String, dynamic>?, 'Weeks 5-8', Colors.blue),
              _buildGrowthPhase(pathway['phase_3_weeks_9_12'] as Map<String, dynamic>?, 'Weeks 9-12', Colors.purple),
            ],
          ],
        ),
      ),
    );
  }

  Widget _buildGrowthPhase(Map<String, dynamic>? phase, String label, MaterialColor color) {
    if (phase == null) return const SizedBox.shrink();
    final goal = phase['goal'] ?? '';
    final activities = (phase['activities'] as List<dynamic>?) ?? [];
    final metric = phase['success_metric'] ?? '';

    return Container(
      margin: const EdgeInsets.only(bottom: 8),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: color.shade900.withValues(alpha: 0.3),
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: color.shade700),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              Container(
                padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 2),
                decoration: BoxDecoration(
                  color: color.shade800,
                  borderRadius: BorderRadius.circular(4),
                ),
                child: Text(label, style: TextStyle(fontSize: 11, fontWeight: FontWeight.bold, color: color.shade200)),
              ),
              const SizedBox(width: 8),
              Expanded(child: Text(goal, style: TextStyle(fontWeight: FontWeight.w500, fontSize: 13, color: Colors.grey[300]))),
            ],
          ),
          if (activities.isNotEmpty) ...[
            const SizedBox(height: 8),
            ...activities.map((a) => Padding(
              padding: const EdgeInsets.only(bottom: 4),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Icon(Icons.check_box_outline_blank, size: 14, color: color.shade400),
                  const SizedBox(width: 8),
                  Expanded(child: Text(a.toString(), style: TextStyle(fontSize: 12, color: Colors.grey[300]))),
                ],
              ),
            )),
          ],
          if (metric.isNotEmpty) ...[
            const SizedBox(height: 8),
            Row(
              children: [
                Icon(Icons.flag, size: 14, color: color.shade400),
                const SizedBox(width: 4),
                Expanded(child: Text('Success: $metric', style: TextStyle(fontSize: 11, color: color.shade300))),
              ],
            ),
          ],
        ],
      ),
    );
  }

  Widget _buildSpiritualFormationCard(Map<String, dynamic> insight) {
    final category = insight['category'] ?? 'Category';
    final level = insight['current_level'] ?? 'Unknown';
    final observation = insight['detailed_observation'] ?? '';
    final markersPresent = (insight['maturity_markers_present'] as List<dynamic>?) ?? [];
    final markersMissing = (insight['maturity_markers_missing'] as List<dynamic>?) ?? [];
    final questions = (insight['mentor_discussion_questions'] as List<dynamic>?) ?? [];

    return Card(
      margin: const EdgeInsets.only(bottom: 12),
      color: Colors.grey[900],
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                Icon(Icons.psychology, color: Colors.purple.shade400),
                const SizedBox(width: 8),
                Expanded(child: Text(category, style: const TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: Colors.white))),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
                  decoration: BoxDecoration(
                    color: Colors.purple.shade900.withValues(alpha: 0.5),
                    borderRadius: BorderRadius.circular(12),
                  ),
                  child: Text(level, style: TextStyle(fontSize: 12, color: Colors.purple.shade300)),
                ),
              ],
            ),
            if (observation.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text(observation, style: TextStyle(fontSize: 13, color: Colors.grey[300])),
            ],
            if (markersPresent.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text('✓ Maturity Markers Present:', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.green.shade400)),
              const SizedBox(height: 4),
              Wrap(
                spacing: 8,
                runSpacing: 4,
                children: markersPresent.map((m) => Chip(
                  label: Text(m.toString(), style: TextStyle(fontSize: 11, color: Colors.green.shade200)),
                  backgroundColor: Colors.green.shade900.withValues(alpha: 0.3),
                  padding: EdgeInsets.zero,
                  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                )).toList(),
              ),
            ],
            if (markersMissing.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text('○ Markers to Develop:', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.orange.shade400)),
              const SizedBox(height: 4),
              Wrap(
                spacing: 8,
                runSpacing: 4,
                children: markersMissing.map((m) => Chip(
                  label: Text(m.toString(), style: TextStyle(fontSize: 11, color: Colors.orange.shade200)),
                  backgroundColor: Colors.orange.shade900.withValues(alpha: 0.3),
                  padding: EdgeInsets.zero,
                  materialTapTargetSize: MaterialTapTargetSize.shrinkWrap,
                )).toList(),
              ),
            ],
            if (questions.isNotEmpty) ...[
              const SizedBox(height: 16),
              Text('Discussion Questions:', style: TextStyle(fontWeight: FontWeight.w600, fontSize: 12, color: Colors.grey[400])),
              const SizedBox(height: 8),
              ...questions.map((q) => Container(
                margin: const EdgeInsets.only(bottom: 8),
                padding: const EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.grey[850],
                  borderRadius: BorderRadius.circular(8),
                  border: Border(left: BorderSide(color: Colors.purple.shade400, width: 3)),
                ),
                child: Text('"$q"', style: TextStyle(fontSize: 13, fontStyle: FontStyle.italic, color: Colors.grey[300])),
              )),
            ],
          ],
        ),
      ),
    );
  }
}
