// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTzy7Z-LaX4wC1EH3k-MR4sbH2hiIFmAE',
    appId: '1:557349072084:web:a5393068afff6edcd79f41',
    messagingSenderId: '557349072084',
    projectId: 'only-blv',
    authDomain: 'only-blv.firebaseapp.com',
    storageBucket: 'only-blv.firebasestorage.app',
    measurementId: 'G-7J46XRRX35',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDq56oQMUrdLxJeENHTDxjNbHGlyOBKI6Y',
    appId: '1:557349072084:android:c306d5e94598c9d1d79f41',
    messagingSenderId: '557349072084',
    projectId: 'only-blv',
    storageBucket: 'only-blv.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzyzCLht3piyygJ0kDFYaj5PCvtF75AX4',
    appId: '1:557349072084:ios:b6bbc9054f3b224bd79f41',
    messagingSenderId: '557349072084',
    projectId: 'only-blv',
    storageBucket: 'only-blv.firebasestorage.app',
    iosClientId: '557349072084-7o7b4svm919irfjcfg0clgvif8t94rab.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTroothAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzyzCLht3piyygJ0kDFYaj5PCvtF75AX4',
    appId: '1:557349072084:ios:b6bbc9054f3b224bd79f41',
    messagingSenderId: '557349072084',
    projectId: 'only-blv',
    storageBucket: 'only-blv.firebasestorage.app',
    iosClientId: '557349072084-7o7b4svm919irfjcfg0clgvif8t94rab.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTroothAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTzy7Z-LaX4wC1EH3k-MR4sbH2hiIFmAE',
    appId: '1:557349072084:web:9b113d2741efd9f3d79f41',
    messagingSenderId: '557349072084',
    projectId: 'only-blv',
    authDomain: 'only-blv.firebaseapp.com',
    storageBucket: 'only-blv.firebasestorage.app',
    measurementId: 'G-ZVPYY0B1QN',
  );
}
